# =========================================================
# 022_combine_gof_chunks.R
# Combine GOF chunk files into family-level GOF tables
# =========================================================
#
# This script:
#   - reads GOF chunk files generated by 021_extract_gof_features.R;
#   - combines chunks by true family;
#   - writes one GOF table per true family;
#   - optionally removes chunk files after successful combination.
#
# Required previous steps:
#   scripts/000_config.R
#   scripts/010_simulate_samples.R
#   scripts/020_extract_features.R
#   scripts/021_extract_gof_features.R
# =========================================================

library(dplyr)
library(tibble)
library(arrow)


# ---------------------------------------------------------
# Repository root check
# ---------------------------------------------------------

root_dir <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)

config_path <- file.path(root_dir, "outputs", "config", "config_main.rds")

if (!file.exists(file.path(root_dir, "R")) ||
    !file.exists(file.path(root_dir, "scripts")) ||
    !file.exists(config_path)) {
  stop(
    "[022] This script must be run from the FADS_AI repository root ",
    "after scripts/000_config.R has been executed.\n",
    "Current working directory: ", root_dir
  )
}


# ---------------------------------------------------------
# Load helper functions and configuration
# ---------------------------------------------------------

source(file.path(root_dir, "R", "fun_io.R"))

config <- read_rds(config_path)
paths  <- config$paths


# ---------------------------------------------------------
# Settings
# ---------------------------------------------------------

family_levels <- config$experiment$families
gof_dir <- paths$gof

ensure_dir(gof_dir)

combine_batch_size <- if (!is.null(config$gof$combine_batch_size)) {
  as.integer(config$gof$combine_batch_size)
} else {
  50L
}

cleanup_gof_chunks_after_combine <- if (!is.null(config$gof$cleanup_chunks_after_combine)) {
  isTRUE(config$gof$cleanup_chunks_after_combine)
} else {
  FALSE
}

if (combine_batch_size <= 0) {
  stop("[022] combine_batch_size must be positive.")
}


# ---------------------------------------------------------
# Atomic parquet writer
# ---------------------------------------------------------

save_parquet_atomic <- function(df, path) {
  
  tmp <- paste0(path, ".tmp_", Sys.getpid(), "_", sample.int(1e6, 1))
  
  if (file.exists(tmp)) {
    unlink(tmp, force = TRUE)
  }
  
  save_parquet(df, tmp)
  
  if (file.exists(path)) {
    unlink(path, force = TRUE)
  }
  
  ok <- file.rename(tmp, path)
  
  if (!ok) {
    ok2 <- file.copy(tmp, path, overwrite = TRUE)
    unlink(tmp, force = TRUE)
    
    if (!ok2) {
      stop("[022] Failed to move parquet into place: ", path)
    }
  }
  
  invisible(path)
}


# ---------------------------------------------------------
# Validate parquet file
# ---------------------------------------------------------

is_valid_parquet_table <- function(path, required_cols = character()) {
  
  if (!file.exists(path)) {
    return(FALSE)
  }
  
  out <- tryCatch(
    {
      tbl <- arrow::read_parquet(path)
      is.data.frame(tbl) &&
        nrow(tbl) > 0 &&
        all(required_cols %in% names(tbl))
    },
    error = function(e) FALSE
  )
  
  isTRUE(out)
}


# ---------------------------------------------------------
# Combine chunk files for one family
# ---------------------------------------------------------

combine_chunk_family <- function(files_i, out_path, batch_size = 50L) {
  
  if (length(files_i) == 0) {
    stop("[022] No chunk files supplied to combine_chunk_family().")
  }
  
  if (batch_size <= 0) {
    stop("[022] batch_size must be positive.")
  }
  
  files_i <- sort(files_i)
  
  batch_dir <- paste0(out_path, "_combine_batches")
  ensure_dir(batch_dir)
  
  # Remove stale batch files from previous interrupted runs.
  stale_batches <- list.files(batch_dir, pattern = "\\.parquet$", full.names = TRUE)
  
  if (length(stale_batches) > 0) {
    unlink(stale_batches, force = TRUE)
  }
  
  batch_ids <- ceiling(seq_along(files_i) / batch_size)
  
  for (bb in sort(unique(batch_ids))) {
    
    files_bb <- files_i[batch_ids == bb]
    
    log_msg(
      "[022] Combining batch ", bb,
      " | files = ", length(files_bb)
    )
    
    tbl_bb <- dplyr::bind_rows(lapply(files_bb, read_parquet))
    
    batch_path <- file.path(batch_dir, sprintf("batch_%03d.parquet", bb))
    
    save_parquet_atomic(tbl_bb, batch_path)
    
    rm(tbl_bb)
    invisible(gc())
  }
  
  batch_files <- sort(
    list.files(batch_dir, pattern = "\\.parquet$", full.names = TRUE)
  )
  
  if (length(batch_files) == 0) {
    stop("[022] No intermediate batch files were created for: ", out_path)
  }
  
  fam_tbl <- dplyr::bind_rows(lapply(batch_files, read_parquet))
  
  if (!"sample_id" %in% names(fam_tbl)) {
    stop("[022] Combined GOF table lacks required column 'sample_id': ", out_path)
  }
  
  save_parquet_atomic(fam_tbl, out_path)
  
  rm(fam_tbl)
  invisible(gc())
  
  unlink(batch_dir, recursive = TRUE, force = TRUE)
  
  invisible(out_path)
}


# ---------------------------------------------------------
# Process each true family
# ---------------------------------------------------------

combined_families <- character(0)

for (fam in family_levels) {
  
  pattern_i <- paste0("^gof_table_", fam, "_chunk_[0-9]{5}\\.parquet$")
  
  files_i <- sort(
    list.files(gof_dir, pattern = pattern_i, full.names = TRUE)
  )
  
  if (length(files_i) == 0) {
    log_msg("[022] Skipping family ", fam, ": no GOF chunk files found.")
    next
  }
  
  valid_chunks <- vapply(
    files_i,
    is_valid_parquet_table,
    logical(1),
    required_cols = c("sample_id")
  )
  
  if (!all(valid_chunks)) {
    bad_files <- basename(files_i[!valid_chunks])
    
    stop(
      "[022] Invalid GOF chunk files found for family ",
      fam,
      ": ",
      paste(bad_files, collapse = ", ")
    )
  }
  
  log_msg(
    "[022] Combining GOF chunks for family ", fam,
    " | n_chunks = ", length(files_i)
  )
  
  out_path <- file.path(gof_dir, paste0("gof_table_", fam, ".parquet"))
  
  combine_chunk_family(
    files_i = files_i,
    out_path = out_path,
    batch_size = combine_batch_size
  )
  
  if (!is_valid_parquet_table(out_path, required_cols = c("sample_id"))) {
    stop("[022] Combined GOF table appears invalid: ", out_path)
  }
  
  log_msg(
    "[022] Saved combined GOF table for family ", fam,
    " | path = ", out_path
  )
  
  combined_families <- c(combined_families, fam)
  
  if (cleanup_gof_chunks_after_combine) {
    unlink(files_i, force = TRUE)
    log_msg("[022] Removed GOF chunk files for family ", fam)
  }
}


# ---------------------------------------------------------
# Final checks
# ---------------------------------------------------------

if (length(combined_families) == 0) {
  stop(
    "[022] No GOF tables were combined. ",
    "Run scripts/021_extract_gof_features.R first."
  )
}

missing_families <- setdiff(family_levels, combined_families)

if (length(missing_families) > 0) {
  log_msg(
    "[022] Warning: no combined GOF table was created for families: ",
    paste(missing_families, collapse = ", ")
  )
}


# ---------------------------------------------------------
# Session info
# ---------------------------------------------------------

save_session_info(
  file.path(paths$gof, "session_info_022.txt")
)

log_msg("[022] 022_combine_gof_chunks.R finished successfully.")